image: node:latest

pages:
  cache:
    paths:
      - node_modules/

  script:
    - npm i hexo-cli -g
    - npm i
    - hexo clean
    - hexo g
  artifacts:
    paths:
      - public
  only:
    - master
